### ISSUE TITLE
Excessive memory usage with k8s

### ISSUE THREAD

**Issue by miadabrin** [containous/traefik#2376]
I have been using the latest version and surprisingly the memory usage seems a lot higher than before. Currently 5GB on a single server which goes to 20GB eventually over two days. It really seems too much

### Do you want to request a *feature* or report a *bug*?

a Possible bug

### What did you do?

Used traefik with kuberenetes with lots of ingress rules for different host names

### What did you expect to see?

Less memory usage

### What did you see instead?

an excessive amount of memory consumed by treafik

### Output of `traefik version`: (_What version of Traefik are you using?_)

1.4.2

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
defaultEntryPoints = ["http"]
logLevel = "WARN"
MaxIdleConnsPerHost = 1000

[entryPoints]
  [entryPoints.http]
  address = ":80"
  compress = true
    [entryPoints.http.redirect]
      regex = "^http://www[.](.*)"
      replacement = "http://$1"

**Comment by timoreimann** [comment]
This may or may not be related to #1064. Does your request flow possibly involve file transfers of non-trivial sizes?

**Comment by miadabrin** [comment]
@timoreimann  Not currently at least. files are 1MB tops

**Comment by timoreimann** [comment]
Also, would you have a chance to try out the latest master build? We refactored parts of the Ingress handling logic a while ago, and my basic benchmarks didn't show any memory problems. We'll need more real world usage though to be sure.

If master is too much on the edge for you, I can also offer to backport the Kubernetes improvements to a custom version of the 1.4 branch. Shouldn't be too hard as the refactoring is fairly isolated.

Let me know if any of this is an option to you. I also planned to invest time on my own into further investigations, though right now I'm a bit short on bandwidth.

**Comment by miadabrin** [comment]
I will try it and let you know the results

**Comment by miadabrin** [comment]
@timoreimann same behaviour

**Comment by timoreimann** [comment]
@miadabrin thanks for the feedback.

What we will need is a profile that tells us where our memory is spent. Do you think you could do that somehow? Happy to assist if you need help.

**Comment by miadabrin** [comment]
@timoreimann would like to help for sure. how can I profile it?

**Comment by timoreimann** [comment]
@miadabrin turns out profiling for memory consumption in Traefik isn't possible without modifying the code as of now. :( Specifically, we need to enable pprof and ideally expose a pprof handler.

I can try to carve out some time to put together a quick supporting hack based on Traefik 1.4. Would that work for you?

**Comment by miadabrin** [comment]
@timoreimann Would be glad to help. But please note the stack is in production. I can't just test anything on it

**Comment by timoreimann** [comment]
@miadabrin thanks. I'll focus on making it as little invasive as possible and for sure to have an option to turn it on/off quickly.

**Comment by timoreimann** [comment]
@miadabrin based on my recently submitted PR #2428, I have backported support for Go pprof HTTP handlers to the 1.4 branch and pushed a custom Docker Hub image at `timoreimann/traefik:v1.4.3-pprof`. Could you please start that image with the `--debug` option (or `debug = true` in the TOML configuration file), wait for the high memory usage to surface, and then send me the profile data available at 

```
<your Traefik endpoint>:<the web provider port>/debug/pprof/heap
```

e..g., `http://traefik.comp.com:8080/debug/pprof/heap`. This will hopefully allow us to see where the memory is spent.

Thanks in advance.

**Comment by miadabrin** [comment]
@timoreimann Unfortunately I was not able to test it with the 1.4.3 version. But seems it has aggrevated with the recent 1.4.5 version. is there still a way to profile it? It currently takes over 40 GB on each of our servers

**Comment by timoreimann** [comment]
@miadabrin I need to backport the pprof patch for the latest 1.4.5, but that shouldn't be difficult. Will try to push an updated image tonight.

It might also be interesting to know that I have done virtually nothing over the past two weeks except for profiling and benchmarking our configuration of Traefik. We found a few things affecting performance (some of which I'll push fixes for) but nothing on the order of 40 GB memory consumption. The actual profile depends on a lot of factors, however, including traffic patterns and providers / middlewares being used. So chances are our setup diverges too much from the problematic one you're experiencing.

Thanks again for helping out on the performance front. Will report back again once the custom image is ready.

**Comment by miadabrin** [comment]
@timoreimann I am using a kubernetes cluster with lots of ingress rules (above 7000 currently). it might be a caching issue or something. The thing is it gradually increases overtime which indicates that it is either a memory leak(not my best guess) or it can be an aggressive caching mechanism with no invalidation which occurs over user usage

**Comment by timoreimann** [comment]
The Kubernetes object caching part is mostly done by client-go, the official Kubernetes API library for Go. We still run a fairly old version, so I could imagine that we're hitting some bug or lacking some optimizations either of which a newer client version might be able to help with.

The heap analysis should bring clarity as to where the memory is spent.

**Comment by timoreimann** [comment]
@miadabrin I just pushed `timoreimann/traefik:v1.4.5-pprof` into Docker Hub.

**Comment by miadabrin** [comment]
@timoreimann I deployed it on our servers with these options 
`
        - --kubernetes
        - --consul
        - --consul.endpoint=172.16.0.1:8500
        - --debug
        - --web
`
butI cannot view anything on the 8080 port. Getting a 404

**Comment by miadabrin** [comment]
@timoreimann it seems to timeout for some reason. and sometimes just gives 404. I can give you the address so you can view it yourself. But I can't make it public. do you have a twitter handle?

**Comment by miadabrin** [comment]
@timoreimann here are the image options
```
        - --kubernetes
        - --consul
        - --consul.endpoint=172.16.0.1:8500
        - --debug
        - --web

```

**Comment by timoreimann** [comment]
@miadabrin hmm, strange that it doesn't work for you. I did find one more bug in my image (I forgot to apply #2523) but it shouldn't have led to a 404. You'll need the fix anyway though, which is why I just pushed an update to `timoreimann/traefik:v1.4.5-pprof-patch1`. Please make sure you use that version.

For the sake of completion, here's how I verified that things work: I ran the image locally via

```
docker run -p 8080:8080 --rm timoreimann/traefik:v1.4.5-pprof --debug --web
```

and checked that I could reach both http://127.0.0.1:8080/debug/pprof/ (the pprof overview page) as well as http://127.0.0.1:8080/debug/pprof/heap (the heap profile).

If the issue continues to persist, feel free to DM me on Twitter. It's the same handle as on Github.

**Comment by miadabrin** [comment]
@timoreimann Still the same. Sent you the details via twitter

**Comment by timoreimann** [comment]
Turned out that the debug switch had to be enabled on Consul. After that, we got the profile data.

The largest heap consumer with over 84% is Golang's regular expression library:

```
(pprof) top10
Showing nodes accounting for 2.55GB, 92.63% of 2.76GB total
Dropped 175 nodes (cum <= 0.01GB)
Showing top 10 nodes out of 86
      flat  flat%   sum%        cum   cum%
    2.32GB 84.35% 84.35%     2.32GB 84.35%  regexp.(*bitState).reset /usr/local/Cellar/go/1.9.2/libexec/src/regexp/backtrack.go
    0.06GB  2.09% 86.45%     0.06GB  2.09%  regexp/syntax.(*compiler).rune /usr/local/Cellar/go/1.9.2/libexec/src/regexp/syntax/compile.go
    0.04GB  1.42% 87.86%     0.04GB  1.42%  regexp.progMachine /usr/local/Cellar/go/1.9.2/libexec/src/regexp/exec.go
    0.03GB  0.96% 88.83%     0.03GB  0.96%  github.com/containous/traefik/vendor/k8s.io/client-go/plugin/pkg/client/auth/oidc.newOIDCAuthProvider /Users/treimann/Development/traefik/src/github.com/containous/traefik/vendor/k8s.io/client-go/plugin/pkg/client/auth/oidc/oidc.go
    0.02GB  0.82% 89.65%     0.02GB  0.82%  type..hash.github.com/containous/traefik/vendor/github.com/coreos/go-oidc/oidc.ProviderConfigSyncer <autogenerated>
    0.02GB  0.69% 90.34%     0.02GB  0.69%  reflect.mapaccess /usr/local/Cellar/go/1.9.2/libexec/src/runtime/hashmap.go
    0.02GB  0.64% 90.98%     0.02GB  0.64%  type..eq.struct { github.com/containous/traefik/vendor/github.com/coreos/go-oidc/oidc.val *net/url.URL; github.com/containous/traefik/vendor/github.com/coreos/go-oidc/oidc.name string } <autogenerated>
    0.02GB   0.6% 91.58%     0.03GB  1.00%  github.com/containous/traefik/vendor/k8s.io/client-go/tools/cache.(*threadSafeMap).Index /Users/treimann/Development/traefik/src/github.com/containous/traefik/vendor/k8s.io/client-go/tools/cache/thread_safe_store.go
    0.01GB  0.53% 92.11%     0.01GB  0.53%  github.com/containous/traefik/vendor/github.com/gorilla/websocket.(*Conn).WriteControl /Users/treimann/Development/traefik/src/github.com/containous/traefik/vendor/github.com/gorilla/websocket/conn.go
    0.01GB  0.51% 92.63%     0.11GB  4.15%  github.com/containous/traefik/vendor/k8s.io/client-go/pkg/apis/certificates/v1alpha1.addConversionFuncs.func1 /Users/treimann/Development/traefik/src/github.com/containous/traefik/vendor/k8s.io/client-go/pkg/apis/certificates/v1alpha1/conversion.go
```

A detailed look reveals that we are spending the vast majority of memory in some `visited` variable:

```
(pprof) list reset
Total: 2.76GB
ROUTINE ======================== regexp.(*bitState).reset in /usr/local/Cellar/go/1.9.2/libexec/src/regexp/backtrack.go
    2.32GB     2.32GB (flat, cum) 84.35% of Total
         .          .     74:// ncap is the number of captures.
         .          .     75:func (b *bitState) reset(end int, ncap int) {
         .          .     76:	b.end = end
         .          .     77:
         .          .     78:	if cap(b.jobs) == 0 {
  363.12MB   363.12MB     79:		b.jobs = make([]job, 0, 256)
         .          .     80:	} else {
         .          .     81:		b.jobs = b.jobs[:0]
         .          .     82:	}
         .          .     83:
         .          .     84:	visitedSize := (len(b.prog.Inst)*(end+1) + visitedBits - 1) / visitedBits
         .          .     85:	if cap(b.visited) < visitedSize {
    1.97GB     1.97GB     86:		b.visited = make([]uint32, visitedSize, maxBacktrackVector/visitedBits)
         .          .     87:	} else {
         .          .     88:		b.visited = b.visited[:visitedSize]
         .          .     89:		for i := range b.visited {
         .          .     90:			b.visited[i] = 0
         .          .     91:		}
         .          .     92:	}
         .          .     93:
         .          .     94:	if cap(b.cap) < ncap {
       1MB        1MB     95:		b.cap = make([]int, ncap)
         .          .     96:	} else {
         .          .     97:		b.cap = b.cap[:ncap]
         .          .     98:	}
         .          .     99:	for i := range b.cap {
         .          .    100:		b.cap[i] = -1
```

The call graph shows that we end up at this part of the code through gorilla/mux when the routes are being matched:

![call_graph](https://user-images.githubusercontent.com/694826/34114366-e899ed8c-e412-11e7-822c-8ea0a4f1d83f.gif)

I suppose those 7000 Ingresses are not managed as efficiently by gorilla/mux as we'd like them to be.

**Comment by timoreimann** [comment]
@miadabrin do you know if your Ingress rules are mostly regex- or prefix-based? While gorilla/mux always uses regular expressions under the hood, I wonder if a possible focus on true prefixes could improve things.

**Comment by miadabrin** [comment]
@timoreimann well there is both kinds. but mostly ithey are like {subdomain}.somemaindomain.com and www.{subdomain}.somemaindoman.com

**Comment by emilevauge** [comment]
@miadabrin so mainly `HostRegexp` right ?

**Comment by miadabrin** [comment]
Please not that they are fed from kubernetes. we don't specifically define frontend rules for them. I have to read the traefik code to answer for sure

**Comment by miadabrin** [comment]
like this one

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: client-ing-miad
spec:
  backend:
    serviceName: default-http-backend
    servicePort: 80
  rules:
  - host: miadabrin.ir
    http:
      paths:
      - path: /
        backend:
          serviceName: client-theme-svc-themec
          servicePort: 5000
  - host: www.miadabrin.ir
    http:
      paths:
      - path: /
        backend:
          serviceName: client-theme-svc-themec
          servicePort: 5000
  - host: miadabrin.ir
    http:
      paths:
      - path: /admin/
        backend:
          serviceName: shop-admin-general-svc
          servicePort: 80
  - host: www.miadabrin.ir
    http:
      paths:
      - path: /admin/
        backend:
          serviceName: shop-admin-general-svc
          servicePort: 80
```

**Comment by timoreimann** [comment]
The default rule type is path prefix then.

**Comment by traefiker** [comment]
Closed by #2592.

**Comment by timoreimann** [comment]
I'll build a custom version of Traefik 1.4 so that we can check whether it truly solves the problem. Reopening until we have clarity.

**Comment by timoreimann** [comment]
@miadabrin do you have a chance to try out `timoreimann/traefik:v1.4.5-pprof-patch2`? This one brings a fix that's supposed to reduce memory usage. Note though that it only applies if you are not using a regular expression-based rule type, which none of your Ingresses in https://github.com/containous/traefik/issues/2376#issuecomment-352519344 do.

**Comment by miadabrin** [comment]
@timoreimann Sure will try it right away and will let you know the results

**Comment by miadabrin** [comment]
@timoreimann It has dropped significantly at the start ( to 1GB on each server) I will let it be running to check how it does in a longer interval. But seems to be an amazing job already. Thanks you!

**Comment by miadabrin** [comment]
Update: Still the same usage (about 1.2GB but seems to be stable over user usage) So I think it's a fix. will post another update in 12 hours.

**Comment by timoreimann** [comment]
@miadabrin that sounds very promising. Looking forward to your next update.

**Comment by miadabrin** [comment]
Update: Still the same usage . I think it's a fix. Although the traffic was higher than usual (it was a special day in the country our project is running) the usage has not changed too much. it has stayed at the range of 1GB to 1.2GB. 

Good job traefik team and special thanks to @timoreimann for following it up

**Comment by timoreimann** [comment]
Appreciate the testing you did for us, @miadabrin.

The fix will be officially included in the upcoming 1.5 release.

**Comment by emilevauge** [comment]
Thanks @miadabrin for helping us fixing this one :+1: 
A big :clap: for @timoreimann for his very detailed analysis !
