### ISSUE TITLE
Traefik doesn't handle empty acme.json file well :)

### ISSUE THREAD

**Issue by sokoow** [containous/traefik#3135]
### Do you want to request a *feature* or report a *bug*?

BUG

### What did you do?

had an empty acme.json file, had this: 

### What did you expect to see?

Working traefik... somehow

### What did you see instead?

```
alse ProxyProtocol:<nil> ForwardedHeaders:0xc420625ba0} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s" 
time="2018-04-05T07:46:06Z" level=info msg="Loading ACME Account..." 
time="2018-04-05T07:46:06Z" level=error msg="Error creating TLS config: unexpected end of JSON input" 
time="2018-04-05T07:46:06Z" level=fatal msg="Error preparing server: unexpected end of JSON input" 
```

### Output of `traefik version`: (_What version of Traefik are you using?_)
latest

**Comment by tha80** [comment]
Have the same problem, when acme.json doesn't exist (at initial startup):

```
infrastructure_traefik.1.wg12qg5cjylp@node01 | time="2018-04-05T09:16:39Z" level=warning msg="Failed to read new account, ACME data conversion is not available : open /store/acme.json: no such file or directory"
infrastructure_traefik.1.wg12qg5cjylp@node01 | time="2018-04-05T09:16:39Z" level=error msg="Error starting provider *acme.Provider: unable to get ACME account : open /store/acme.json: no such file or directory"
```

**Comment by timothyallan** [comment]
Glad it's not just me...

```
traefik_1  | time="2018-04-06T05:26:07Z" level=warning msg="Failed to read new account, ACME data conversion is not available : open /etc/traefik/acme/acme.json: no such file or directory
```

```
version: '3.3'

services:
  traefik:
    image: traefik:1.6
    networks:
      - appnet
    command:
      - --api 
      - --docker 
      - --docker.watch 
      - --docker.domain=docker.localhost
      - --docker.exposedbydefault=false 
      - --logLevel=DEBUG 
.... etc etc
    ports:
      - "443:443"
      - "80:80"
      - "8080:8080"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefikdata:/etc/traefik/acme
      - /dev/null:/traefik.toml

volumes:
  traefikdata:

**Comment by nathanaherne** [comment]
I have the same issue on a Traefik container built today

`time="2018-04-08T05:40:19Z" level=error msg="Error starting provider *acme.Provider: unable to get ACME account : open acme.json: no such file or directory"`

I am running Traefik on docker swarm using traefik:1.6-alpine

**Comment by nmengin** [comment]
Hello guys,

Many thanks for your interest in the project.

@sokoow : Your issue seems to be a bug which is fixed in v1.6-RC1. If you are using an older version you can : 
- Upgrade the Træfik version
- Or edit your `acme.json` file to add `{}`.

@tha80, @timothyallan, @nathanaherne : The error message appears when the `acme.json` cannot be opened by Træfik. Can you provide you entire configuration (Træfik options and docker) in the way to reproduce the issue?

Thanks in advance.

**Comment by traefiker** [comment]
Closed by #3156.

**Comment by SvenDowideit** [comment]
@nmengin I still get a similar error as above with rc6 - if i fail to specify `--acme.storage`

```
infrastructure_traefik.1.wg12qg5cjylp@node01 | time="2018-04-05T09:16:39Z" level=warning msg="Failed to read new account, ACME data conversion is not available : open : no such file or directory"
infrastructure_traefik.1.wg12qg5cjylp@node01 | time="2018-04-05T09:16:39Z" level=error msg="Error starting provider *acme.Provider: unable to get ACME account : open : no such file or directory"
```

**Comment by nmengin** [comment]
Hello @SvenDowideit .

The directory has to be created to allow Traefik to create the ACME json file.
Can you try to create the parent directory before to start Træfik?

If you have still the issue please open a new issue to join our [Slack workspace](https://traefik.herokuapp.com/) for more [community #support](https://traefik.slack.com/messages/C0CDT22PJ/).

**Comment by SvenDowideit** [comment]
@nmengin yup - if i create "the directory" then this error goes away - but... the error message should really suggest that this is the problem - and I didn't see any requirement to create a dir in the docs either.

**Comment by nmengin** [comment]
Thank you for your feedback @SvenDowideit .

> the error message should really suggest that this is the problem - and I didn't see any requirement to create a dir in the docs either.

Yep, I have to improve the documentation, I will precise it (but feel free to open a PR with this the precision if you want :wink: )

> `--acme.storage File or key used for certificates storage` feels like something that could be optional - especially in the docker image (which is what I'm using)

Using a default path was an option we studied with the team. We prefer to keep this option as mandatory in the way to allow users to know where the ACME certificates are stored in the way to create a volume and keep the certificates on the host even if the container is removed.

If a volume is not created, when they restart the container, Træfik will generate new certificates and, maybe, users will have `rate limit` error. 
That's why, for the moment, we prefer keep it as mandatory.

I hope I reponsed to all of your questions.
Many thanks to use Træfik and contribute to our project.

**Comment by gdheller42** [comment]
Still have the same error with v1.6.1 ?? !

time="2018-05-20T04:10:42Z" level=error msg="Error starting provider *acme.Provider: unable to get ACME account : open acme.storage=/etc/traefik/acme/acme.json: no such file or directory"

**Comment by holms** [comment]
Got the same problem with 1.6.3 and 1.6 and in 1.5
```level=error msg="Failed to read new account, ACME data conversion is not available : open '/etc/traefik/acme/acme.json': no such file or directory"```

**Comment by Flyffies** [comment]
Just got it with 1.6.6

Here is the Log:

Traefik version v1.6.6 built on 2018-08-20_01:10:06PM
Stats collection is disabled.
Help us improve Traefik by turning this feature on :)
More details on: https://docs.traefik.io/basics/#collected-data
Failed to read new account, ACME data conversion is not available : open traefik-certificates/acme.json: no such file or directory

**Comment by mwschall** [comment]
I had trouble bootstrapping a new docker-compose configuration when mounting a volume for acme as a file, ala `traefik-acme:acme.json`. So I mounted the volume as an empty folder instead and set `acme.storage=/acme/certs.json`, letting traefik create the file as it saw fit.

**Comment by pc-star** [comment]
setting the storage as @trajano suggested, and keep the key permissions at 600 did the trick for me.

**Comment by sphirke** [comment]
I am also getting the same error:

> time="2019-02-26T13:55:57Z" level=error msg="Failed to read new account, ACME data conversion is not available : open etc/traefik/acme/acme.json: no such file or directory"
> time="2019-02-26T13:55:57Z" level=error msg="Unable to add ACME provider to the providers list: unable to get ACME account : open etc/traefik/acme/acme.json: no such file or directory"

Traefik Service:
```
loadbalancer:
        image: traefik
        command:
            - --api
            - "--entrypoints=Name:http Address::80 Redirect.EntryPoint:https"
            - "--entrypoints=Name:https Address::443 TLS"
            - --defaultentrypoints=http,https
            - --acme
            - --acme.storage=etc/traefik/acme/acme.json
            - --acme.entryPoint=https
            - --acme.httpChallenge.entryPoint=http
            - --acme.onHostRule=true
            - --acme.onDemand=false
            - --docker
            - --docker.swarmMode
            - --docker.domain=mydomain.ca
            - --docker.watch
        ports:
            - "80:80"
            - "18080:443"
            - "8080:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /opt/traefik/traefik.toml:/traefik.toml
            - /etc/traefik/acme/acme.json:/acme.json
```

Traefik.toml

```
logLevel = "ERROR"
defaultEntryPoints = ["http", "https"]
[web]
address = ":8080"
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
[acme]
email = "username@domain.com"
storageFile = "/etc/traefik/acme/acme.json"
entryPoint = "https"
onDemand = false
OnHostRule = true
  [acme.httpChallenge]
  entryPoint = "http"
[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "bmc.com"
watch = true
exposedbydefault = false
```

My application is running on HTTPS.

@pc-star @trajano @traefiker @nmengin 
What I am missing here please help me.

**Comment by burtsevyg** [comment]
Work with "--acme.storage=/acme.json"
