### ISSUE TITLE
instanceIds can have at most 100 items

### ISSUE THREAD

**Issue by Dgadavin** [containous/traefik#3627]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
Started Traefik

### What did you expect to see?
Working traefik

### What did you see instead?
```
time="2018-07-16T12:35:53Z" level=error msg="Unable to describe container instances: InvalidParameterException: instanceIds can have at most 100 items.\n\tstatus code: 400, request id: c74a8f28-88f4-11e8-bad3-0f447d092cd4"
```

### Output of `traefik version`: (_What version of Traefik are you using?_)
```Version:      v1.7.0-rc1
Codename:     maroilles
Go version:   go1.10.3
Built:        2018-07-09_03:03:16PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
[web]
address = ":8080"
readOnly = true

[ecs]
clusters = ["my-ecs-cluster-name"]
watch = true
domain = "example.com"
autoDiscoverClusters = false
refreshSeconds = 15
exposedByDefault = true
region = "eu-west-1"
```
I see the same issue #1210 but I look in code and there is no chunks in it.

**Comment by mmatur** [comment]
Hi @Dgadavin,

Thanks for your interest in Træfik. 

I confirm your issue. 
I am working on a fix #3629 

I built and push a docker image for this fix `mmatur/traefik:fix-3627`. 

Could you have a look please?

**Comment by Dgadavin** [comment]
Yes. Will do. @mmatur Thanks.

**Comment by Dgadavin** [comment]
We have such error. 
```
standard_init_linux.go:190: exec user process caused "no such file or directory"
```
We run docker  container in ECS on Amazon Linux instances.

**Comment by mmatur** [comment]
Should be better now @Dgadavin. I pushed a new image few minutes ago.

```console
$ docker pull mmatur/traefik:fix-3627
```

```console
$ docker run mmatur/traefik:fix-3627 traefik version
Version:      ce6afdae09928e812489acc1483dcb92149e8891
Codename:     cheddar
Go version:   go1.10.3
Built:        2018-07-17_07:26:51AM
OS/Arch:      linux/amd64
```

**Comment by Dgadavin** [comment]
@mmatur  We check several times. Redeploy several times but the error is still here. 
```
time="2018-07-17T08:55:26Z" level=info msg="Using TOML configuration file /etc/traefik/traefik.toml"
time="2018-07-17T08:55:26Z" level=warning msg="web provider configuration is deprecated, you should use these options : api, rest provider, ping and metrics"
time="2018-07-17T08:55:26Z" level=warning msg="web option is ignored if you use it with one of these options : api, rest provider, ping or metrics"
time="2018-07-17T08:55:26Z" level=info msg="Traefik version ce6afdae09928e812489acc1483dcb92149e8891 built on 2018-07-17_07:26:51AM"
time="2018-07-17T08:55:26Z" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://docs.traefik.io/basics/#collected-data\n"
time="2018-07-17T08:55:26Z" level=debug msg="Global configuration loaded "
time="2018-07-17T08:55:26Z" level=info msg="Preparing server http &{Address::80 TLS:<nil> Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] WhiteList:<nil> Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc4205ee0e0} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s"
time="2018-07-17T08:55:26Z" level=info msg="Preparing server traefik &{Address::8080 TLS:<nil> Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] WhiteList:<nil> Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc4205ee100} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s"
time="2018-07-17T08:55:26Z" level=info msg="Starting provider configuration.ProviderAggregator
{}
"
time="2018-07-17T08:55:26Z" level=info msg="Starting server on :80"
time="2018-07-17T08:55:26Z" level=info msg="Starting server on :8080"
time="2018-07-17T08:55:26Z" level=info msg="Starting provider *ecs.Provider {\"Watch\":true,\"Filename\":\"\",\"Constraints\":[],\"Trace\":false,\"TemplateVersion\":2,\"DebugLogGeneratedTemplate\":false,\"Domain\":\"example.com\",\"ExposedByDefault\":false,\"RefreshSeconds\":15,\"Clusters\":[\"docker-cluster-staging-Cluster-FSMCK7C5WR3B\"],\"Cluster\":\"\",\"AutoDiscoverClusters\":false,\"Region\":\"eu-west-1\",\"AccessKeyID\":\"\",\"SecretAccessKey\":\"\"}"
time="2018-07-17T08:55:26Z" level=debug msg="ECS Clusters: [docker-cluster-staging-Cluster-FSMCK7C5WR3B]"
time="2018-07-17T08:55:26Z" level=error msg="Unable to describe container instances: InvalidParameterException: instanceIds can have at most 100 items.\n\tstatus code: 400, request id: 260c0fce-899f-11e8-a67c-27704d6c9fc2"
```

**Comment by mmatur** [comment]
@Dgadavin thanks for your feedback. After some investigation I found an other issue. 
It should be fixed by https://github.com/containous/traefik/pull/3629/commits/095d67cfaf9ca9a1ec122dd81160d0b86d547791


Could you have a look please? Docker image is up-to-date 
```console
$  docker run mmatur/traefik:fix-3627 traefik version
Version:      095d67cfaf9ca9a1ec122dd81160d0b86d547791
Codename:     cheddar
Go version:   go1.10.3
Built:        2018-07-17_09:17:14AM
OS/Arch:      linux/amd64
```

**Comment by mmatur** [comment]
@Dgadavin We can continue our discussion and tests on [Slack workspace. ](https://slack.traefik.io/)

**Comment by Dgadavin** [comment]
Now it's work like a charm.
