### ISSUE TITLE
Bad default values in configuration

### ISSUE THREAD

**Issue by emilevauge** [containous/traefik#427]
Default values for `EntryPoints` and `DefaultEntryPoints` are not set correctly:
https://github.com/containous/traefik/blob/master/traefik.go#L117
This ends up with error:
```
No entrypoint defined for frontend ..., defaultEntryPoints:[]. Skipping it
```

**Comment by erolg** [comment]
This issue effect to Docker Compose demo

**docker logs demo_traefik_1**
`...
time="2016-06-11T04:09:33Z" level=debug msg="Last docker config received more than 2s, OK" 
time="2016-06-11T04:09:33Z" level=debug msg="Creating frontend frontend-Host-whoami-docker-localhost" 
time="2016-06-11T04:09:33Z" level=error msg="No entrypoint defined for frontend frontend-Host-whoami-docker-localhost, defaultEntryPoints:[]. Skipping it" `

**Comment by emilevauge** [comment]
@erolg which version of traefik?

**Comment by erolg** [comment]
@emilevauge, treafik:latest from docker hub

docker images traefik

```
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
traefik             latest              bf7f4f01be40        12 days ago         19.91 MB

```
**docker exec demo_traefik_1 /traefik version**

`2016/06/12 18:34:56 v1.0.0-rc1 built on the 2016-05-30_10:25:50PM`

**Comment by rebaseTraefik** [comment]
Please update to the latest image :) this issue is solved.

Le dim. 12 juin 2016 20:39, Erol Guzoğlu <notifications@github.com> a
écrit :

**Comment by erolg** [comment]
sorry I updated my image but forget to remove old container.

**Comment by makeittotop** [comment]
I'm under the impression that the "defaultEntryPoint" is optional and if undefined it should fall back to "http". Based on this assumption I'd say that this issue still exists in the latest traefik binary - v1.2.3.

I didn't have the defaultEntryPoint defined as "http" in the traefik.toml file and I was hooking up traefik to consulCatalog and didn't define the entryPoint in the consul service either.

This is the error I got :-
No entrypoint defined for frontend <...>, defaultEntryPoints:[]

**Comment by kurt---** [comment]
I can confirm the error in the docker-compose-demo (https://github.com/containous/traefik/issues/427#issuecomment-225335669)
It only works for me by setting 
```
# Entrypoints to be used by frontends that do not specify any entrypoint.
# Each frontend can specify its own entrypoints.
#
# Optional
# Default: ["http"]
#
defaultEntryPoints = ["http"]
```

it does not work with
```
# Entrypoints to be used by frontends that do not specify any entrypoint.
# Each frontend can specify its own entrypoints.
#
# Optional
# Default: ["http"]
#
# defaultEntryPoints = ["http", "https"]
```

**Comment by armpogart** [comment]
Same here on latest version of traefik, if I don't specify `defaultEntryPoints` explicitly, it doesn't work.

**Comment by dkinzer** [comment]
I ran into the same issue using the docker image for the latest build.

**Comment by michaelarnauts** [comment]
This issue isn't fixed. I still have to add `defaultEntryPoints = ["http"]` to my traefik.toml file for the docker-compose to work.

**Comment by ldez** [comment]
@micaelmbagira Fixed in 1.5, see #2501

**Comment by michaelarnauts** [comment]
... what was released about 40 minutes ago. Thanks! :) Sorry for the spam!
