### ISSUE TITLE
Traefik not closing Forward Auth Connections

### ISSUE THREAD

**Issue by GHDiscard** [containous/traefik#6229]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I am using a middleware with forwardauth to point at an authelia container. This is something I did in traefik 1.7 too, but in 2.0 after a few days all pages respond with a 500 error.

Restarting either the traefik or authelia containers fix the problem temporarily. 

The traefik log file shows:
```
time="2020-01-15T05:06:59Z" level=debug msg="Error calling http://authelia:8080/api/verify?rd=https://auth.<removed>.cloud/#/. Cause: Get http://authelia:8080/api/verify?rd=https://auth.<removed>.cloud/#/: dial tcp 172.19.0.4:8080: connect: cannot assign requested address" middlewareName=authelia@file middlewareType=ForwardedAuthType
```

Running wget http://authelia:8080/ from within the container fails with a similar message. I checked netstat, it contained over 26,000 established connections to the authelia container in the format:

```
tcp        0      0 172.19.0.6:42110        172.19.0.4:8080         ESTABLISHED
tcp        0      0 172.19.0.6:42166        172.19.0.4:8080         ESTABLISHED
tcp        0      0 172.19.0.6:43354        172.19.0.4:8080         ESTABLISHED
```

For some reason the connections to the forwardauth are not being closed.

I have looked through the traefik and authelia issues and cannot find a similar bug. I have only noticed this more recently with higher useage containers, but having removed this and watched netstat, it still seems to rise and doesnt fall significantly over time with a fresh container.

### What did you expect to see?
That traefik would continue to proxy to containers

### What did you see instead?
Error 500, as above

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
# docker run traefik version
Version:      2.1.3
Codename:     cantal
Go version:   go1.13.6
Built:        2020-01-21T17:30:29Z
OS/Arch:      linux/amd64

```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

<details>
<summary>traefik.yml</summary>

```yaml
api:
  insecure: true
  dashboard: true
  debug: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: traefik
  file:
    directory: /conf/
    watch: true

entryPoints:
  web:
    address: ":80"
    transport:
  web-secure:
    address: ":443"
    transport:

certificatesResolvers:
  le:
    acme:
      email: <removed>
      storage: acme.json
      tlsChallenge: {}

serversTransport:
  insecureSkipVerify: true

log:
  level: DEBUG
  filePath: "/var/log/traefik.log"
```

</details>

<details>
<summary>conf/middlewares.yml</summary>

```yaml
http:
  middlewares:
    https-redirect:
      redirectScheme:
        scheme: https

    default-headers:
      headers:
        frameDeny: false
        customFrameOptionsValue: ""
        sslRedirect: true
        # browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        accessControlAllowOrigin: "*"
        customResponseHeaders:
          X-Frame-Options: ""

    authelia:
      forwardAuth:
        address: "http://authelia:8080/api/verify?rd=https://auth.<removed>.cloud/#/"
        tls:
          insecureSkipVerify: true
          trustForwardHeader: true

    web-default-chain:
      chain:
        middlewares:
        - https-redirect
        - default-headers
        - authelia
        - x-frame-block

    web-secure-default-chain:
      chain:
        middlewares:
        - default-headers
        - authelia
        - x-frame-block

    auth-default-chain:
      chain:
        middlwares:
        - default-headers
        - https-redirect

    x-frame-block:
      headers:
        customResponseHeaders:
          X-Frame-Options: ""
        customRequestHeaders:
          X-Frame-Options: ""
```

</details>

<details>
<summary>traefik docker compose</summary>

```yaml
version: '3'

services:
  traefik:
    container_name: traefik
    restart: always
    ports:
      - '8080:8080'
      - '80:80'
      - '443:443'
    volumes:
      - './files/traefik/traefik.yml:/etc/traefik/traefik.yml'
      - './files/traefik/traefik_config_files/enabled/:/conf/'
      - './files/traefik/ssl/:/ssl/'
      - './files/traefik/acme.json:/acme.json'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './files/traefik/traefik.log:/var/log/traefik.log'
    image: "traefik:latest"
    command:
      - "--serverstransport.insecureskipverify=true"
    networks:
      traefik:

networks:
  traefik:
    external: true
```

</details>

<details>
<summary>authelia docker compose</summary>

```yaml
version: '3'

services:
  authelia:
    image: clems4ever/authelia:master
    container_name: authelia
    restart: always
    volumes:
      - ./files/config.minimal.yml:/etc/authelia/configuration.yml:ro
      - ./files/users_database.yml:/etc/authelia/users_database.yml:rw
      - ./files/storage.db:/etc/authelia/storage.db:rw
      - /tmp/authelia:/tmp/authelia
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth-web.rule=Host(`auth.<removed>.cloud`)"
      - "traefik.http.routers.auth-web.entrypoints=web"
      - "traefik.http.routers.auth-web.middlewares=web-default-chain@file"
      - "traefik.http.routers.auth-web-secure.rule=Host(`auth.<removed>.cloud`)"
      - "traefik.http.routers.auth-web-secure.entrypoints=web-secure"
      - "traefik.http.routers.auth-web-secure.middlewares=auth-default-chain@file"
      - "traefik.http.routers.auth-web-secure.tls=true"
      - "traefik.http.routers.auth-web-secure.tls.certresolver=le"
    expose:
      - 8080
    networks:
     - web
     - mail

networks:
  web:
    external:
      name: traefik
  mail:
    external: true
```

</details>

<details>
<summary>Sample proxied container (httpbin) docker compose</summary>

```yaml
version: '3'

services:
  httpbin:
    container_name: httpbin
    image: kennethreitz/httpbin
    restart: always
    expose:
      - 80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.httpbin-web.rule=Host(`httpbin.<removed>.cloud`)"
      - "traefik.http.routers.httpbin-web.entrypoints=web"
      - "traefik.http.routers.httpbin-web.middlewares=web-default-chain@file"
      - "traefik.http.routers.httpbin-web-secure.rule=Host(`httpbin.<removed>.cloud`)"
      - "traefik.http.routers.httpbin-web-secure.entrypoints=web-secure"
      - "traefik.http.routers.httpbin-web-secure.middlewares=web-secure-default-chain@file"
      - "traefik.http.routers.httpbin-web-secure.tls=true"
      - "traefik.http.routers.httpbin-web-secure.tls.certresolver=le"
    networks:
     - web

networks:
  web:
    external:
      name: traefik
```

</details>

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

See log entry at top, repeated here:
```
time="2020-01-15T05:06:59Z" level=debug msg="Error calling http://authelia:8080/api/verify?rd=https://auth.<removed>.cloud/#/. Cause: Get http://authelia:8080/api/verify?rd=https://auth.<removed>.cloud/#/: dial tcp 172.19.0.4:8080: connect: cannot assign requested address" middlewareName=authelia@file middlewareType=ForwardedAuthType
```

Thank you for your time, happy to provide more info as requested

**Comment by ldez** [comment]
Hello,

the code of the `forwardAuth` is roughly the same between v1 and v2:
- https://github.com/containous/traefik/blob/v1.7/middlewares/auth/forward.go
- https://github.com/containous/traefik/blob/v2.0/pkg/middlewares/auth/forward.go

So I don't think the problem come from Traefik.

**Comment by james-d-elliott** [comment]
For additional information I use the same backend on k8s with the Traefik 1.7 ingress without issue. I'm going to attempt using 2.1 to see what happens. 

@GHDiscard what exact version of Traefik are you using? And can you post on the issue I mentioned this one from with some information about your Authelia setup?

**Comment by james-d-elliott** [comment]
So I have managed to narrow this down to the tls.insecureSkipVerify=true setting, causes this issue in versions 1.7.20, 2.0.0, 2.1.0, and 2.1.3. This only occurs on forward auth providers that are not using https. I've yet to replicate it on any others.

Considering authelia is designed to be a backend service with https provided by another ingress container this setting should be off. The reason for it occurring when this setting is on is however strange.

**Comment by juliens** [comment]
@james-d-elliott thanks for all your clarification, i tried a fix and i pushed an image based on v2.1 (juliens/traefik:fix-socket-fauth) , do you think you can try with this image? I'm going to try on my side, but I don't have an authelia configuration yet, so it may take some time.

**Comment by james-d-elliott** [comment]
It didn't seem to fix it , and no debug log entries stand out. I am about to sleep but this should get you going:

./docker-compse.yml: https://hastebin.com/gedimedoci.yaml
./authelia/config/configuration.yml: https://hastebin.com/busaroseyo.yaml
./authelia/config/users.yml: https://hastebin.com/jucinirosu.yaml

**Comment by juliens** [comment]
Thanks for all this configuration files, it helps me a lot, and I think I found the bug. Can you try with `juliens/traefik:fix-socket-fauth-2` and confirm it works for you too?

**Comment by james-d-elliott** [comment]
Yes, that's it. "watch nsenter -t [docker container pid] -n netstat" now shows a stable list of connections that close and open appropriately.

**Comment by ZyanKLee** [comment]
thanks @james-d-elliott and @juliens for your work to find this issue! I really appreciate it.

**Comment by james-d-elliott** [comment]
No worries, I am sure everyone appreciates you reporting it and providing all the detail that you did (at least made it super easy for me to figure out why it was happening).

@GHDiscard You can fix your issue by removing the tls key from your authelia forwardauth middleware. trustForwardHeader is a subkey of forwardauth, unless I'm mistaken, and insecureSkipVerify is 1. not a production setting, and 2. not necessary for a http forwardauth provider.

**Comment by traefiker** [comment]
Closed by #6267.

**Comment by traefiker** [comment]
Closed by #6273.
