### ISSUE TITLE
Traefix does not start when LetsEncrypt does not work

### ISSUE THREAD

**Issue by bvis** [containous/traefik#791]
Today we have suffered an issue when we tried to move our traefik tasks from one node to another. The scheduler has tried to launch the service in another node but it failed because of Letsencrypt failures.

```console
$ docker inspect 9lb8xxxxxx (traefik task)
...
"Status": {
            "Timestamp": "2016-10-31T13:11:04.538031123Z",
            "State": "failed",
            "Message": "started",
            "Err": "task: non-zero exit (1)",
            "ContainerStatus": {
                "ContainerID": "b86862bdc9563a440c36861d4756055b1e26e4a0b08146bd00793c87d0d95b84",
                "ExitCode": 1
            }
        },
...
$ docker logs 551fc96db70c
time="2016-10-31T13:03:44Z" level=error msg="Error creating TLS config get directory at 'https://acme-v01.api.letsencrypt.org/directory': acme: Error 502 - urn:acme:error:serverInternal - The service is down for maintenance or had an internal error. Check https://letsencrypt.status.io/ for more details."
time="2016-10-31T13:03:44Z" level=fatal msg="Error preparing server: get directory at 'https://acme-v01.api.letsencrypt.org/directory': acme: Error 502 - urn:acme:error:serverInternal - The service is down for maintenance or had an internal error. Check https://letsencrypt.status.io/ for more details."
```
And it was because of a failure in Letsencrypt.
![image](https://cloud.githubusercontent.com/assets/580682/19862508/eae149e0-9f90-11e6-844e-b25c6f6e63bb.png)

It provoked a downtime on our proxied services.
But even our system at the moment didn't need to generate any TLS certificate traefik failed its starting process.

Could this error be transformed to a warning or let the traefik server run when the Letsencrypt service is not working? As I said we didn't need any new TLS certificate, because all of them were stored in a shared volume in our cluster.  In this case the consequence is that even the services exposed in the 80 port were not working.

**Comment by emilevauge** [comment]
@bvis Indeed, traefik *shoud* start even if LE is down. Will look into that.

**Comment by trecloux** [comment]
@bvis do you have the full log for this issue ?

**Comment by emilevauge** [comment]
@trecloux no logs are needed here, the issue can be reproduced easily :)

**Comment by trecloux** [comment]
@emilevauge with a bad let's encrypt API URL ?

**Comment by emilevauge** [comment]
@trecloux exactly :)

**Comment by kobeyu** [comment]
Let's encrypt is down again today. As @bvis found, this is stopping Traefik from starting, and causing downtime for all our sites. I've removed the `[acme]` part from `traefik.toml` to get things going (http only). Is this likely to be fixed?

(Sorry if this sounds like nagging, it's just I'm otherwise really happy with traefik and it'd be a shame to have to use something else because of this)

**Comment by mholt** [comment]
FWIW, In Caddy we now handle this by renewing 30 days out, but allowing the server to start if it's 7 days out from expiration. This should give a window of about 3 weeks to restart your server when there's some network blockage or downtime.

(This was only an issue for fully managed/automatic certificates; configurations which specify their own certificates or disabled HTTPS were not susceptible to this behavior in the first place.)

**Comment by bvis** [comment]
As @kobeyu says, it's happening again. 

My cluster does not work as expected because of a 3rd party problem, it should never affect this way to traefik. I think it should just affect the generation/renovation of certificates. Current stored certificates should work without any issue.

```
time="2017-05-19T14:39:31Z" level=error msg="Error creating TLS config: get directory at 'https://acme-v01.api.letsencrypt.org/directory': failed to get json "https://acme-v01.api.letsencrypt.org/directory": Get https://acme-v01.api.letsencrypt.org/directory: net/http: request canceled (Client.Timeout exceeded while awaiting headers)"
```

```# curl -I https://acme-v01.api.letsencrypt.org/directory
HTTP/1.1 504 Gateway Time-out
Server: AkamaiGHost
Mime-Version: 1.0
Content-Type: text/html
Content-Length: 176
Expires: Fri, 19 May 2017 14:43:51 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Fri, 19 May 2017 14:43:51 GMT
Connection: keep-alive```

**Comment by np** [comment]
Is there a way to tune the timeout parameter? I guess that at the moment it would be helpful for them as all the amount of tools hammering their API must be significant.

**Comment by Yajo** [comment]
I think this should happen:

1. Traefik starts **always**.
2. Traefik serves the sites **always**.
3. Traefik encrypts https connection **always**.
   - If there is ACME connection, handle renewals as usual and use good certs.
   - If there is no ACME connection:
     - If we have an older cert for the site, use that one (even if it is expired).
     - Otherwise (maybe a new site or a new Traefik instance), use a self-generated cert.

This comes out from some *red lines* I believe Traefik should not cross:

- Leaving the sites unreachable.
- Leaving the sites unencrypted.

**Comment by fabiorauber** [comment]
Totally agree @Yajo

**Comment by mvdstam** [comment]
@emilevauge Is this still on your radar?

**Comment by ldez** [comment]
@mvdstam We have not solved this issue in 1.3. Release coming soon 😃

**Comment by mvdstam** [comment]
Thanks @idez, hope to see this fixed in a subsequent release since it's kind of a critical issue. Cheers.

**Comment by celebrion** [comment]
Looks like this is still an issue, right?
When running Traefik via Docker, everything (web access to all containers via Traefik) dies if Traefik is unable to reach the acme-servers even once. Restarting/rebuilding the Traefik container doesn't solve the problem, but restarting Docker entirely makes everything come up again. Happens a few times per week, so should be nice to solve it somehow.

After restart of Traefik:
```
traefik_1  | time="2017-08-04T19:20:22Z" level=info msg="Traefik version v1.3.5 built on 2017-08-01_04:18:59PM"
traefik_1  | time="2017-08-04T19:20:22Z" level=info msg="Using TOML configuration file //traefik.toml"
traefik_1  | time="2017-08-04T19:20:22Z" level=info msg="Preparing server http &{Network: Address::80 TLS:<nil> Redirect:0xc4202707b0 Auth:<nil> Compress:false}"
traefik_1  | time="2017-08-04T19:20:22Z" level=info msg="Preparing server https &{Network: Address::443 TLS:0xc4202b64e0 Redirect:<nil> Auth:<nil> Compress:false}"
traefik_1  | time="2017-08-04T19:20:22Z" level=info msg="Starting server on :80"
traefik_1  | time="2017-08-04T19:20:22Z" level=info msg="Loading ACME Account..."
traefik_1  | time="2017-08-04T19:20:22Z" level=info msg="Loaded ACME config from store acme.json"
traefik_1  | time="2017-08-04T19:20:32Z" level=warning msg="Error checking new version: Get https://update.traefik.io/repos/containous/traefik/releases: dial tcp: lookup update.traefik.io on 127.0.0.11:53: read udp 127.0.0.1:36450->127.0.0.11:53: i/o timeout"
traefik_1  | time="2017-08-04T19:20:32Z" level=error msg="Error creating TLS config: get directory at 'https://acme-v01.api.letsencrypt.org/directory': failed to get json "https://acme-v01.api.letsencrypt.org/directory": Get https://acme-v01.api.letsencrypt.org/directory: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"
traefik_1  | time="2017-08-04T19:20:32Z" level=fatal msg="Error preparing server: get directory at 'https://acme-v01.api.letsencrypt.org/directory': failed to get json "https://acme-v01.api.letsencrypt.org/directory": Get https://acme-v01.api.letsencrypt.org/directory: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"
```

After restart of Docker:
```
traefik_1  | time="2017-08-04T19:27:18Z" level=info msg="Traefik version v1.3.5 built on 2017-08-01_04:18:59PM"
traefik_1  | time="2017-08-04T19:27:18Z" level=info msg="Using TOML configuration file //traefik.toml"
traefik_1  | time="2017-08-04T19:27:18Z" level=info msg="Preparing server http &{Network: Address::80 TLS:<nil> Redirect:0xc420265920 Auth:<nil> Compress:false}"
traefik_1  | time="2017-08-04T19:27:18Z" level=info msg="Preparing server https &{Network: Address::443 TLS:0xc420321920 Redirect:<nil> Auth:<nil> Compress:false}"
traefik_1  | time="2017-08-04T19:27:18Z" level=info msg="Starting server on :80"
traefik_1  | time="2017-08-04T19:27:18Z" level=info msg="Loading ACME Account..."
traefik_1  | time="2017-08-04T19:27:18Z" level=info msg="Loaded ACME config from store acme.json"
traefik_1  | time="2017-08-04T19:27:18Z" level=info msg="Retrieving ACME certificates..."
traefik_1  | time="2017-08-04T19:27:18Z" level=info msg="Starting provider *docker.Provider {"Watch":true,"Filename":"","Constraints":null,"Endpoint":"unix:///var/run/docker.sock","Domain":"docker.local","TLS":null,"ExposedByDefault":false,"UseBindPortIP":false,"SwarmMode":false}"
traefik_1  | time="2017-08-04T19:27:18Z" level=info msg="Retrieved ACME certificates"
traefik_1  | time="2017-08-04T19:27:18Z" level=info msg="Starting provider *server.WebProvider {"Address":":8080","CertFile":"","KeyFile":"","ReadOnly":false,"Statistics":null,"Metrics":null,"Path":"","Auth":null}"
traefik_1  | time="2017-08-04T19:27:18Z" level=info msg="Starting server on :443"
traefik_1  | time="2017-08-04T19:27:18Z" level=info msg="Server configuration reloaded on :80"
traefik_1  | time="2017-08-04T19:27:18Z" level=info msg="Server configuration reloaded on :443"
```

docker-compose.yml:
```
version: '3.1'

services:
  traefik:
    restart: unless-stopped
    image: traefik:1.3.5
    command: --web --docker --docker.domain=docker.local --docker.exposedbydefault=false --logLevel=INFO
    ports:
      - "80:80"
      - "127.0.0.1:8080:8080"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./certs/acme.json:/acme.json
    networks:
      - webgateway


networks:
  webgateway:
    driver: bridge
```

traefik.toml:
```
defaultEntryPoints = ["http", "https"]
  [entryPoints]
    [entryPoints.http]
      address = ":80"
      [entryPoints.http.redirect]
        entryPoint = "https"
    [entryPoints.https]
    address = ":443"
      [entryPoints.https.tls]
[acme]
email = "redacted@mail.address"
storage = "acme.json"
onDemand = true
entryPoint = "https"
```

**Comment by emilecaron** [comment]
Experienced the same issue as @celerion. Caused us a rather unexpected downtime as well.

**Comment by ldez** [comment]
Traefik doesn't start if Let's Encrypt is down but Let's Encrypt  has rarely downtime (1-2 per year).

@celebrion @emilecaron The symptoms you are experiencing differ from those of the original bug submitter.
Seems you have a network problem (maybe related to Docker configuration or something else)

**Comment by mvdstam** [comment]
@ldez 

> Traefik doesn't start if Let's Encrypt is down but Let's Encrypt has rarely downtime (1-2 per year).

Still, this is quite a serious bug as anyone using Traefik and LetsEncrypt is basically depending on LetsEncrypt not having outages. That's quite a dependency.
 That said, is there any chance to get this picked up by the team before the next release? This bug has been reported almost a year ago now, and no time like the present to fix it I guess. 😃

**Comment by ldez** [comment]
@mvdstam I do not minimize the bug, I'm just trying to explain that it's a different problem.

Once again, we are a small team, we have a lot of topics, we try to do the best.

For now, we are not working on this bug, so it will not be fixed by us in the next release.

Anyone can solve this problem by opening a PR, it's open source 😃

**Comment by Schmaddin** [comment]
Hello,

I have a similar issue, but guess it comes from a different problem:
https://acme-staging.api.letsencrypt.org/directory  is online and available.

but I get: traefik_1     | time="2017-08-25T17:10:35+02:00" level=fatal msg="Error preparing server: get directory at 'https://acme-v01.api.letsencrypt.org/directory': failed to get json "https://acme-v01.api.letsencrypt.org/directory": Get https://acme-v01.api.letsencrypt.org/directory: dial tcp: lookup acme-v01.api.letsencrypt.org on 127.0.0.11:53: read udp 127.0.0.1:52227->127.0.0.11:53: read: connection refused"

a curl "https://acme-staging.api.letsencrypt.org/directory" works pretty fine

So this is a intern DNS Resolving Problem?

**Comment by soakes** [comment]
Same problem here running traefik:1.3.8.

**Comment by w3blogfr** [comment]
Seems to have same issue with 1.4

**Comment by traefiker** [comment]
Closed by #2794.

**Comment by bvis** [comment]
Nice! Thanks a lot
