### ISSUE TITLE
1.1.0 kubernetes panic: send on closed channel

### ISSUE THREAD

**Issue by jonaz** [containous/traefik#877]
This has happened twice (2) in the last hour since i upgraded to 1.1.0 in our development cluster. 

The last log message before the panic was:
```
time="2016-11-22T14:43:00Z" level=error msg="Kubernetes connection error failed to decode watch event: GET \"https://127.0.0.1:9443/apis/extensions/v1beta1/ingresses\" : unexpected EOF, retrying in 639.617334ms" 
```

```
panic: send on closed channel

goroutine 4420 [running]:
panic(0xd292c0, 0xc4203f96a0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/containous/traefik/provider/k8s.(*clientImpl).watch.func1.1(0xc42050e900, 0xc420141260, 0xc420221080, 0x26, 0xc420141200)
	/go/src/github.com/containous/traefik/provider/k8s/client.go:280 +0x33f
created by github.com/containous/traefik/provider/k8s.(*clientImpl).watch.func1
	/go/src/github.com/containous/traefik/provider/k8s/client.go:286 +0xbf
```

I run traefik like this:
```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
  labels:
    app: traefik-ingress-lb
spec:
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      terminationGracePeriodSeconds: 30
      hostNetwork: true
      containers:
      - image: traefik:v1.1.0
        name: traefik-ingress-lb
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 1000m
            memory: 500Mi
          requests:
            cpu: 200m
            memory: 100Mi
        ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 8081
        args:
        - --retry.attempts=8
        - --retry
        - --web
        - --web.address=:8081
        - --kubernetes
        - --kubernetes.endpoint=https://127.0.0.1:9443
```

**Comment by jonaz** [comment]
I has happend alot since i updated to 1.1.0 yesterday:
```
Time 	message  	pod_name  
November 23rd 2016, 08:23:35.033	panic: send on closed channel traefik-ingress-controller-jff4x 
November 23rd 2016, 08:20:15.166	panic: send on closed channel traefik-ingress-controller-jff4x 
November 23rd 2016, 08:18:11.736	panic: send on closed channel traefik-ingress-controller-jff4x 
November 23rd 2016, 08:05:05.438	panic: send on closed channel traefik-ingress-controller-d0w7j 
November 23rd 2016, 07:21:34.433	panic: send on closed channel traefik-ingress-controller-jff4x
November 23rd 2016, 06:55:16.236	panic: send on closed channel traefik-ingress-controller-jff4x
November 23rd 2016, 06:12:36.462	panic: send on closed channel traefik-ingress-controller-jff4x
November 23rd 2016, 06:04:28.268	panic: send on closed channel traefik-ingress-controller-jff4x
November 23rd 2016, 05:44:58.866	panic: send on closed channel traefik-ingress-controller-jff4x
November 23rd 2016, 05:36:52.834	panic: send on closed channel traefik-ingress-controller-jff4x
November 23rd 2016, 05:19:39.035	panic: send on closed channel traefik-ingress-controller-jff4x
November 23rd 2016, 04:38:08.234	panic: send on closed channel traefik-ingress-controller-jff4x
November 23rd 2016, 03:36:38.334	panic: send on closed channel traefik-ingress-controller-jff4x
November 23rd 2016, 03:35:08.460	panic: send on closed channel traefik-ingress-controller-jff4x
November 23rd 2016, 03:29:51.734	panic: send on closed channel traefik-ingress-controller-jff4x
November 23rd 2016, 03:26:47.672	panic: send on closed channel traefik-ingress-controller-jff4x
November 23rd 2016, 03:10:05.876	panic: send on closed channel traefik-ingress-controller-66z9z
November 23rd 2016, 01:55:17.676	panic: send on closed channel traefik-ingress-controller-66z9z
November 23rd 2016, 01:18:26.260	panic: send on closed channel traefik-ingress-controller-jff4x
November 23rd 2016, 00:34:45.336	panic: send on closed channel traefik-ingress-controller-jff4x
November 23rd 2016, 00:33:42.360	panic: send on closed channel traefik-ingress-controller-jff4x
November 23rd 2016, 00:06:09.633	panic: send on closed channel traefik-ingress-controller-jff4x
November 23rd 2016, 00:03:05.363	panic: send on closed channel traefik-ingress-controller-jff4x
November 22nd 2016, 23:49:57.108	panic: send on closed channel traefik-ingress-controller-66z9z
November 22nd 2016, 23:06:29.933	panic: send on closed channel traefik-ingress-controller-jff4x
November 22nd 2016, 22:57:24.639	panic: send on closed channel traefik-ingress-controller-zndmv
November 22nd 2016, 22:28:07.783	panic: send on closed channel traefik-ingress-controller-66z9z
November 22nd 2016, 22:23:02.135	panic: send on closed channel traefik-ingress-controller-jff4x
November 22nd 2016, 21:58:46.216	panic: send on closed channel traefik-ingress-controller-d0w7j
November 22nd 2016, 21:35:28.234	panic: send on closed channel traefik-ingress-controller-jff4x
November 22nd 2016, 20:40:51.269	panic: send on closed channel traefik-ingress-controller-jff4x
November 22nd 2016, 19:17:43.383	panic: send on closed channel traefik-ingress-controller-jff4x
November 22nd 2016, 19:12:38.535	panic: send on closed channel traefik-ingress-controller-jff4x
November 22nd 2016, 19:02:29.935	panic: send on closed channel traefik-ingress-controller-jff4x
November 22nd 2016, 17:58:36.634	panic: send on closed channel traefik-ingress-controller-jff4x
November 22nd 2016, 17:49:28.355	panic: send on closed channel traefik-ingress-controller-jff4x
November 22nd 2016, 17:06:51.316	panic: send on closed channel traefik-ingress-controller-d0w7j
November 22nd 2016, 17:04:56.631	panic: send on closed channel traefik-ingress-controller-jff4x
November 22nd 2016, 16:57:43.408	panic: send on closed channel traefik-ingress-controller-zndmv
November 22nd 2016, 16:44:00.741	panic: send on closed channel traefik-ingress-controller-uuwxw
November 22nd 2016, 16:19:41.436	panic: send on closed channel traefik-ingress-controller-uuwxw
November 22nd 2016, 15:49:07.337	panic: send on closed channel traefik-ingress-controller-uuwxw
November 22nd 2016, 15:43:00.936	panic: send on closed channel traefik-ingress-controller-uuwxw
```

**Comment by emilevauge** [comment]
@jonaz I made a fix and pushed a Docker image for testing `containous/traefik:k8s`. If you could test it, that would help a lot :)

**Comment by thaume** [comment]
Hi @emilevauge I had the same problem, just updated my traefik controller (it went smoothly), will let you know how it goes for me. Thanks !

**Comment by jonaz** [comment]
@emilevauge i will try tomorrow at work.

**Comment by emilevauge** [comment]
>is there a commit with diff i can look at to complement the testing? (code review ftw)

Here is the pull request https://github.com/containous/traefik/pull/900

**Comment by jonaz** [comment]
I have deployed containous/traefik:k8s into our development cluster and will give it a few hours now.

**Comment by thaume** [comment]
As a heads up, it has been 15 hours and not a single restart.

**Comment by jonaz** [comment]
There is a problem with the fix. 

containous/traefik:k8s seems ton contain the fix in https://github.com/containous/traefik/pull/874
```
queryParams := map[string]string{"watch": "true", "resourceVersion": resourceVersion}
```

Which means that it will never try do write to errCh (failed to decode watch event: GET) and it will not panic.


So in order to test this fix we need a docker image without the fix from #874.

**Comment by emilevauge** [comment]
@jonaz Yeah, #874 had already been merged. I just pushed `containous/traefik:k8s` disabling the fix.

**Comment by jonaz** [comment]
@emilevauge thanks i'll redeploy that

**Comment by jonaz** [comment]
I have not had any panics the last 5 hours. I will leave it running over the weekend.

**Comment by jonaz** [comment]
It has not crashed yet. So i would consider it fixed.

**Comment by emilevauge** [comment]
Fixed by #900
Thanks @jonaz @thaume for your help :)

**Comment by mthird** [comment]
I've switched to using the containous/traefik:k8s build and still see the decoding issues:

```
2016-11-28T19:57:06.631945394Z time="2016-11-28T19:57:06Z" level=error msg="Kubernetes connection error failed to decode watch event: GET \"https://10.200.0.1:443/apis/extensions/v1beta1/ingresses\" : unexpected EOF, retrying in 300.839227ms" 
2016-11-28T19:58:07.047522776Z time="2016-11-28T19:58:07Z" level=error msg="Kubernetes connection error failed to decode watch event: GET \"https://10.200.0.1:443/apis/extensions/v1beta1/ingresses\" : unexpected EOF, retrying in 316.754354ms" 
2016-11-28T19:59:07.447124736Z time="2016-11-28T19:59:07Z" level=error msg="Kubernetes connection error failed to decode watch event: GET \"https://10.200.0.1:443/apis/extensions/v1beta1/ingresses\" : unexpected EOF, retrying in 535.680986ms" 
2016-11-28T20:00:08.084936902Z time="2016-11-28T20:00:08Z" level=error msg="Kubernetes connection error failed to decode watch event: GET \"https://10.200.0.1:443/apis/extensions/v1beta1/ingresses\" : unexpected EOF, retrying in 511.724881ms" 
```

**Comment by jonaz** [comment]
Yeah if you read my comment you will se why:
https://github.com/containous/traefik/issues/877#issuecomment-262909508

**Comment by mthird** [comment]
The [https://github.com/containous/traefik/issues/877#issuecomment-262911100](comment) from emilevuage indicates the k8s image was updated 3 days ago without the fix.  The image on docker hub also indicates it was updated 3 days ago.

**Comment by emilevauge** [comment]
@mthird the image on github `containous/traefik:k8s` only contains a fix on the panic issue. Nothing wrong if you still get `unexpected EOF` logs, this has been fixed in https://github.com/containous/traefik/pull/874

**Comment by jonaz** [comment]
Yeah thats exacly the point? containous/traefik:k8s must NOT contain the fix from #874 (fix for unexpected EOF). Otherwise we cannot know if this #877 is fixed. Because as i said this is an error in the errorhandlinng. 

This issue is only about fixing "panic: send on closed channel" which was an error depending on errorhanding the unexpected EOF.

**Comment by emilevauge** [comment]
@jonaz race condition ;)

**Comment by mthird** [comment]
Makes sense now.  Will ignore the log entries :)

Thanks!
